filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /app-logs/api.logs.json
    json.keys_under_root: true
    json.add_error_key: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "api-logs-%{+yyyy.MM.dd}"
setup.template.name: "api-logs"
setup.template.pattern: "api-logs-*"